# Site settings
title: Nouman Portfolio
author:
  name: Nouman Ahmad
  email: nouman.laravel@outlook.com
description: "Find me for your online website need"

# Build settings
#remote_theme: jekyll/minima
remote_theme: rosario/kasper
