# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Nouman Portfolio
email: nouman.laravel@outlook.com
description: >- # this means to ignore newlines until "baseurl:"
  I am an experienced website developer with over six years of expertise in designing, developing, and deploying high-quality websites and web applications. My skill set spans across multiple technologies, including PHP, Laravel, Django, Express, and JavaScript. I have a strong foundation in building both front-end and back-end solutions, ensuring seamless functionality and user experiences.
  Throughout my career, I have worked on diverse projects, ranging from small business websites to large-scale enterprise applications. My focus is on delivering scalable, efficient, and reliable solutions tailored to the specific needs of each client.
github_username:  NoumanAhmad448
lang: en-US
logo: /assets/imgs/logo.jpg
open_projects: true

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-feed

include: [_posts]
github_path: https://github.com/NoumanAhmad448/

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
